name = "intstu-nuxt"
main = "./.output/server/index.mjs"
compatibility_date = "2024-01-01"

[site]
bucket = ".output/public"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[env.production]
workers_dev = true

[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]